eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://10.22.64.77:8761/eureka/
  instance:
    hostname: localhost
    
zipkin:
  base-url: http://10.22.64.77:9411/
